FROM grafana/grafana

COPY grafana.ini /etc/grafana/grafana.ini
COPY dashboard.yaml /etc/grafana/provisioning/dashboards/mydashboard.yaml
COPY my-dashboard.json /etc/grafana/provisioning/dashboards/my-dashboard.json